apiVersion: v1
kind: Service
metadata:
  name: project4-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      name: port-kube
      protocol: TCP
  selector:
    app: project-4-udacity
