apiVersion: v1
kind: Service
metadata:
  name: project4-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30039
      name: port-kube
      protocol: TCP
  selector:
    app: project-4-udacity
